apiVersion: 1

datasources:
  - name: UDR-Timescale
    type: postgres
    access: proxy
    url: udr-db:5432
    database: udr
    user: udr
    secureJsonData:
      password: udr_pass
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
